### ISSUE TITLE
Clarification about: When using arrow functions as named exports, explicit return should always be used to maintain consistency with regular functions.

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [u3u/eslint-plugin-arrow-return-style#57]
> When using arrow functions as named exports, explicit return should always be used to maintain consistency with regular functions.

Can you expand in the docs what you mean by this, and what is the purpose?

**Comment by u3u** [comment]
Hi, thank you for your report. This is actually just my personal coding style 😂

👇 Please see the example below:

```tsx
// A simple function with named export
export const getUser = async () => fetch('/api/user').then(res => res.json())

// A React component with named export
export const User = ({ user }) => <u className="no-underline font-medium">{user.name}</u>

// ---
// Compare regular functions, I think they are more intuitive.

export async function getUser() {
  return fetch('/api/user').then(res => res.json())
}

export function User({ user }) {
  // I can add things here at any time.
  return <u className="no-underline font-medium">{user.name}</u>
}
```

When used as named exports, it proves that they are reusable. I hope to maintain a consistent function style, which will also make it easier to add code in the future. My idea is that although implicit return is concise, it is not conducive to expansion, so it is best to use it only in very simple anonymous callback functions.

If you really don't like this, I can add an option to allow disabling it.

**Comment by AndreaPontrandolfo** [comment]
I see what you mean, it mostly make sense. But yeah, a config option for this could be nice

**Comment by u3u** [comment]
Hmm, yes, after all, everyone has different habits. I will add it.

**Comment by u3u** [comment]
https://github.com/u3u/eslint-plugin-arrow-return-style/releases/tag/v1.3.0
The option has been added, and now it should be possible to disable it with 
`/* eslint arrow-return-style/arrow-return-style: ['warn', { namedExportsAlwaysUseExplicitReturn: false }] */` .

**Comment by AndreaPontrandolfo** [comment]
Thank you, that's perfect!
